version: '3.1'

networks: 
    balance:
        driver: overlay

services:
    mongo:
        image: mongo
        restart: always
        ports: 
            - 27017:27017
        networks: 
            - balance
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        networks: 
            - balance
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
    api:
        build: ./
        deploy:
            replicas: 15
            restart_policy:
                max_attempts: 3
                condition: on-failure
            update_config:
                parallelism: 3
                delay: 10s
        ports: 
            - 8081:8080
        networks: 
            - balance
    proxy:
        build: ./nginx/
        ports: 
            - 8080:80
        depends_on: 
            - api
        networks: 
            - balance
        # deploy:
        #     resources:
        #         limits:
        #             cpus: '0.25'
        #             memory: 200M
        #         reservations:
        #             memory: 100M
